### ISSUE TITLE
mini-frame flickers when resizing

### ISSUE THREAD

**Issue by aaronjensen** [muffinmad/emacs-mini-frame#31] opened 2021-02-06 16:08 UTC
There is a bug in Emacs on macOS that causes frames to flicker when they are resized: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46155

There's a patch for it that works for me.

However, when mini-frames are resized, there is still a flicker, which makes me wonder if there's more going on when a min-frame is resized. I've been trying to narrow down a repro, but so far when I actually manually resize a mini-frame, it does not flicker.

Any idea what may cause the flicker? Is it perhaps being hidden and shown any time it resizes?

**Comment by muffinmad** [comment] 2021-02-07 20:10
> There's a patch for it that works for me.
> 
> However, when mini-frames are resized, there is still a flicker

Do you mean that applying the patch doesn't solve the issue with the mini-frame?

> I've been trying to narrow down a repro, but so far when I actually manually resize a mini-frame, it does not flicker.

What causes mini-frame to change size for you? Is it some completion package like icomplete or something?

**Comment by aaronjensen** [comment] 2021-02-07 20:11
> Do you mean that applying the patch doesn't solve the issue with the mini-frame?

Yes

> What causes mini-frame to change size for you? Is it some completion package like icomplete or something?

I'm using selectrum. It changes sizes when there are fewer than the max number of candidates.

**Comment by muffinmad** [comment] 2021-02-08 21:41
@aaronjensen Looks like I found receipt to reproduce minibuffer-only frame flickering:

1. `emacs -Q`
2. `M-: (setq resize-mini-frames t)`
3. `M-: (make-frame '((minibuffer . only)))`
4. `M-x`
5. Type random letters

The minibuffer-only frame flickers once it needs to be resized.

Can you please confirm?

If so, we can update the Emacs bug with the new receipt so @alanthird can provide awesome solution ;)

**Comment by aaronjensen** [comment] 2021-02-08 21:50
Awesome, thanks for the repro. I updated the bug and CC'd you.

**Comment by muffinmad** [comment] 2021-02-12 20:46
I'm closing this as this is fixed in Emacs itself.

**Closed by muffinmad** 2021-02-12 20:46 UTC

**Comment by aaronjensen** [comment] 2021-02-13 00:52
Sounds good. For posterity, the fix isn't merged just yet, but hopefully will be after some testing.

**Comment by aaronjensen** [comment] 2021-02-13 22:46
This is now in Emacs master.
