### ISSUE TITLE
[nativecomp] Mini frame not used unless called directly

### ISSUE THREAD

**Issue by xeals** [muffinmad/emacs-mini-frame#14] opened 2020-05-06 01:03 UTC
I'm not too sure what's going on, but it seems that in my testing the most common user of `read-from-minibuffer` (`completing-read` and co.) are completely ignoring the advice on `read-from-minibuffer`.

```sh
$ emacs --version
GNU Emacs 28.0.50 (nativecomp branch)
```

Reproduction, from `emacs -Q`:

```emacs-lisp
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-refresh-contents)
(package-install 'mini-frame)
(mini-frame-mode +1)
```

 - in `ielm`: `(read-from-minibuffer "test: ")` uses the mini-frame as expected
 - in `ielm`: `(completing-read "test: " '(a b))` uses the regular minibuffer
 - <kbd>M-: `(read-from-minibuffer "test: ")`</kbd> uses the regular minibuffer again
 - `execute-extended-command` uses the regular minibuffer

From my regular configuration, `ivy-mode` *does* end up making a mini-frame (behind the regular ivy window), but no other completing-read mode I've tried does (among `icomplete`, `selectrum`, `fido`, and none).

**Comment by muffinmad** [comment] 2020-05-06 06:01
Besides `M-:` behavior, which is expected (see `mini-frame-ignore-commands`), all other use cases creates mini-frame for me.

But I'm not using nativecomp branch.

Can you please check it on regular Emacs build?

**Comment by xeals** [comment] 2020-05-06 08:17
Confirmed it works fine on another machine using regular 28.0.50, both from no and with my own config.

Have tried using `mini-frame-mode` with the file compiled, byte-compiled, and straight evaluating the source and running it; same results. 

Pinned the problem to something not loaded as quickly as it needs to be in `minibuffer.el`, as re-evaluating the source file makes it work perfectly. I'll work on narrowing it down so I can work out what needs to change to support it, but in short we can chalk the issue up to native compilation.

**Comment by bbuccianti** [comment] 2020-08-25 22:22
@xeals Did you find how to make mini-frame work with native-comp?

**Comment by xeals** [comment] 2020-08-27 08:06
@bbuccianti I never solved this, no. I chalked it up as a limitation of the advice system (see my last answer). I'm no longer using native-comp so I can't really help further with this.

**Comment by aaronjensen** [comment] 2021-02-13 15:58
Has this been reported upstream?

**Comment by aaronjensen** [comment] 2021-02-13 18:33
For what it's worth, I cannot reproduce this with native-comp.

**Comment by muffinmad** [comment] 2021-02-14 20:18
@aaronjensen Thank you very much for checking this!

I'm closing this now.

**Closed by muffinmad** 2021-02-14 20:18 UTC
