### ISSUE TITLE
`C-g` doesn't return focus visually

### ISSUE THREAD

**Issue by sulami** [muffinmad/emacs-mini-frame#24] opened 2020-12-09 19:02 UTC
Focus is returned in that input is being sent to the correct window, but the visual indicators show all windows as inactive.

I haven't had time to dig into this yet, otherwise I might be able to submit a PR for this in due time.

**Comment by muffinmad** [comment] 2020-12-09 19:54
What operating system are you using and what Emacs version?

**Comment by sulami** [comment] 2020-12-10 08:02
> What operating system are you using and what Emacs version?

macOS, MacPorts Emacs (in GUI).

**Comment by muffinmad** [comment] 2020-12-10 08:21
Please, provide some screenshot and the receipt to reproduce the issue.

What I tried:

1. `emacs -Q`
2. `M-x load-file mini-frame.el`
3. `M-x mini-frame-mode`
4. `M-x`

<img width="589" alt="Знімок екрана 2020-12-10 о 10 14 00" src="https://user-images.githubusercontent.com/2702727/101740003-fbf9e900-3ad0-11eb-87f7-1ccd6caa8abc.png">

5. `C-g`

Original window remains active:

<img width="589" alt="Знімок екрана 2020-12-10 о 10 14 20" src="https://user-images.githubusercontent.com/2702727/101740062-0d42f580-3ad1-11eb-9552-95bab7ce0ba6.png">

Checked in GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2020-08-16 built on Traviss-Mac.local
Repository revision: 9e359802c7255f59d9a53f7b75b0f1058a589352
Repository branch: HEAD
Windowing system distributor 'Apple Inc.', version 10.16.0
System Description:  macOS 11.0.1

**Comment by sulami** [comment] 2020-12-10 09:09
Interestingly enough I cannot reproduce with `-Q`. I'll binary search
through my installed packages[1] to find the culprit at some point when
I get the time.

Consider this invalid in the mean time.

[1]: https://github.com/sulami/dotfiles/blob/master/emacs/.emacs.d/straight/versions/default.el

**Comment by SebastienWae** [comment] 2020-12-16 09:56
The issue is `doom-modeline`, I'm looking for a solution, I'll update if I find something.

**Comment by Stebalien** [comment] 2021-01-23 18:58
I've found that the following code fixes the issue:

```elisp
  (add-hook 'window-selection-change-functions #'doom-modeline-set-selected-window)
```

Looking at the focus history, it appears that on quit:

1. Focus is returned to the previously selected window.
2. Focus is then re-directed to the main frame's minibuffer.
3. Focus is finally returned to the previously selected window.

I've filed an issue upstream https://github.com/seagle0128/doom-modeline/issues/412, but ideally focus wouldn't bounce around like that. I'm not sure why `mini-frame` has this issue, but `posframe` doesn't.

**Comment by muffinmad** [comment] 2021-01-25 21:32
>  I'm not sure why `mini-frame` has this issue, but `posframe` doesn't.

It's because the `posframe`'s frame does not accept focus and don't have to restore it.

The option to accept focus added to `posframe` with this notice :)
https://github.com/tumashu/posframe/blob/0f2d8603662a3a868bced5f158305e609fbb6081/posframe.el#L502

**Comment by muffinmad** [comment] 2021-01-27 14:19
Looks like the issue is solved in [doom-modeline](https://github.com/seagle0128/doom-modeline/issues/412) so I'm closing this.

**Closed by muffinmad** 2021-01-27 14:19 UTC
